name: testapp
description: A new Flutter project.
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'  # ✅ Added correct SDK constraint

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ✅ Add flutter_local_notifications package
  flutter_local_notifications: ^16.3.2  
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image1.png
