// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkBIyVmhuG6hopoKKk0KUy2PipjsxR8T4',
    appId: '1:424142164788:web:2d6a9207b4f4b3675d8b61',
    messagingSenderId: '424142164788',
    projectId: 'timemate-4a69a',
    authDomain: 'timemate-4a69a.firebaseapp.com',
    databaseURL: 'https://timemate-4a69a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timemate-4a69a.firebasestorage.app',
    measurementId: 'G-E2YJ2SXD2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNKxYNHB15xO3fSUi0K8_LH5ig4-JLw1o',
    appId: '1:424142164788:android:4366560d4d78e1745d8b61',
    messagingSenderId: '424142164788',
    projectId: 'timemate-4a69a',
    databaseURL: 'https://timemate-4a69a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timemate-4a69a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx7qv0NyW8is6z832i0_f4C6WKR7Uxvuk',
    appId: '1:424142164788:ios:203420de80e948ab5d8b61',
    messagingSenderId: '424142164788',
    projectId: 'timemate-4a69a',
    databaseURL: 'https://timemate-4a69a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timemate-4a69a.firebasestorage.app',
    iosClientId: '424142164788-10c7db4393sorc2dcanpu48t4gd3cful.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx7qv0NyW8is6z832i0_f4C6WKR7Uxvuk',
    appId: '1:424142164788:ios:203420de80e948ab5d8b61',
    messagingSenderId: '424142164788',
    projectId: 'timemate-4a69a',
    databaseURL: 'https://timemate-4a69a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timemate-4a69a.firebasestorage.app',
    iosClientId: '424142164788-10c7db4393sorc2dcanpu48t4gd3cful.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkBIyVmhuG6hopoKKk0KUy2PipjsxR8T4',
    appId: '1:424142164788:web:aea47ad8bd4414455d8b61',
    messagingSenderId: '424142164788',
    projectId: 'timemate-4a69a',
    authDomain: 'timemate-4a69a.firebaseapp.com',
    databaseURL: 'https://timemate-4a69a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timemate-4a69a.firebasestorage.app',
    measurementId: 'G-XKX818NP8M',
  );

}